### PR TITLE
Signs and views fix

### LINKED ISSUE #70: Signs again
hi!

A few days ago, I opened an [issue](https://github.com/tectonicus/tectonicus/issues/68) about signs with messy text lines. The reason was that Minecraft 1.9 now uses JSON code instead of plain text fields to store the lines, and the issue was solved with Tectonicus 2.RV. Indeed my test map, created locally with Minecraft 1.9 vanilla was rendered correctly, and I closed the issue.

But... I was a bit fast. My server stores sign text lines in the following format (inspected via NBTExplorer):

    Text1: {"text":""}
    Text2: {"extra":[{"text":SparkLake}]},"text":""}
    Text3: {"extra":[{"text":City}]},"text":""}
    Text4: {"text":""}

and Tectonicus doesn't handle JSON, but just cuts out the string between the first `:` and last `}`. The resulting `signs.js` contains this

    text3: "[{"text":"City"}],"text":"",
    text4: "",
    text1: "",
    text2: "[{"text":"SparkLake"}],"text":"",
    worldPos: new WorldCoord(-753.5, 76.0, -659.5),
    message: "\n[{"text":"SparkLake"}],"text":"\n[{"text":"City"}],"text":"\n"

which isn't valid code. Tectonicus doesn't throw any error message, and when I open the map, I get Google Maps instead :-o

My server runs Spigot 1.9 with Worldedit, Worldguard and PermissionEx.
I guess the first answer is that non-vanilla versions with some plugins may do weird things, _BUT_ when opening this world locally with my Minecraft 1.9 vanilla, all signs are displayed correctly. So, vanilla Minecraft handles the `extra` node correctly, _when it's present_-

I don't know JAVA and can't contribute to the project, but I can code Python. So here is some quick and dirty Python code, which fixes all `signs.js` it finds (recursively) in a directory. And since this is run after Tectonicus, it doesn't fix views. They remain as simple signs.

<pre>
import shutil
import os

OUTPUTDIR="/path/to/renderedMap"

def process(signsfile):
	print("Fixing "+signsfile)
	t={}
	f=open(signsfile)
	g=open(signsfile+"_new", "w")
	for l in f:
		stripped=l.lstrip()
		if(stripped.startswith("text")):
			idx=stripped[0:5]
			s=stripped.split('"')
			txt=""
			if( stripped.count('"')==2): #ordinary line
				txt=s[1]
			else:
				txt=s[4]
			t[idx]=txt
								
			g.write('                %s: "%s",\n'%(idx, txt))

		elif(stripped.startswith("message")):
			g.write('                message: "%(text1)s\\n%(text2)s\\n%(text3)s\\n%(text4)s\\n"\n'%t)
			
		else:
			g.write(l)
		
	f.close()
	g.close()
	shutil.move(signsfile, signsfile+"_backup")
	shutil.move(signsfile+"_new", signsfile)

for root, dirs, files in os.walk(OUTPUTDIR):
	for name in files:
		if name.endswith("signs.js"):
			process(os.path.join(root, name))
</pre>

### PR DESCRIPTION
**Pull request by swbr**
This branch fixes #70  and some other issues.

1. As written there, my signs created with Spigot 1.9 contain this raw data:
<pre>Text1: {"text":""}
Text2: {"extra":[{"text":"SparkLake"}]},"text":""}
Text3: {"extra":[{"text":"City"}]},"text":""}
Text4: {"text":""}</pre>
Though the `extra` key is not used by vanilla MC, it yet is standard and allows e.g. colored text. Now, Tectonicus searches for all `"text"` keys and  concatenates their values. Escaped characters are handled correctly.

2. For view descriptions, special characters were escaped twice / without checking if needed. This caused additional `\` and ignored unicode characters (`\u003c` was replaced by `\\u003c`, which is displayed as `\u003c` instead of `<`)

3. View descriptions were always created from lines 2-4, though line 2 could contain view parameters. Now, descriptions are only created from lines not starting with `#`.

4. View parameters can be written to all four lines, and the white space between `#` and parameter isn't necessary any more (i.e. `#h10` in second line is fine now)

### CODE REVIEW

File: Source/tectonicus/TileRenderer.java [hunk 1]
```diff
@@ -2092,10 +2097,13 @@ public static Point calcLatLong(TileCoord tile, Point screenPos, final int tileW
 	
 	public static String jsEscape(String text)
 	{
-		text = text.replace("\\", "\\\\");	// Replace \ with \\
```
Comment (skoeven) [inline Source/tectonicus/TileRenderer.java]: I undid this as it's still needed for signs in pre-1.8 worlds.

**Comment by skoeven** [comment]
Thanks for working on this!  I made a few changes before I merged it just to fix a few issues.  I made line comments in my commits on GitHub if you're interested in what I changed and why.

It might be worthwhile to eventually support the JSON text options like "extra", "color", etc., but for now just making sure to get the all the text is a good start.

The issues with escaping sign text correctly are caused because I've been trying to maintain compatibility with old Minecraft worlds and the way sign text is stored in world data has changed twice now.  I'm tempted to just rip out all the backwards compatibility stuff because it's not pretty and keeps causing bugs.

**Comment by swbr** [comment]
Hi!
OK, I didn't know that text format already has chanced once before 1.8. Backward compability is always nice for users but hard for developers. 
Anyway, it seems sign text is processed at different locations. For example, the generation of the final text is quite similar for signs and views, but more or less separated.

If you want, I can have a look at it. Do you know when text format changed first time?

**Comment by skoeven** [comment]
> Backward compability is always nice for users but hard for developers.

Exactly, as a user I like being able to use the latest version of Tectonicus to render a map of an old 1.3 server world I played on, but as a developer I don't like the spaghetti code and all the testing I have to do to maintain support for those old versions. 

Sign text gets handled in four locations:
- RawChunk.java - sign text is extracted from the NBT world data
- TileRenderer.java outputSigns() - sign text is concatenated and escaped if from pre-1.8 world
- TileRenderer.java outputViews() - treated similar to outputSigns, but without the '\n' newlines
- blockTypes/Sign.java - text is unescaped for actual rendering on the map

There might be some refactoring we could do here.

The way sign text was stored in the NBT changed from 1.7 to 1.8 and then again from 1.8 to 1.9.  I added version checks in a couple of places to your code changes before I merged the pull request which I think resolved the backwards compatibility issues that I saw.  I've tested signs and views on 1.5, 1.8, and 1.9 worlds and so far everything seems to be working (getting escaped correctly, etc.).

**Comment by Pekkhum** [comment]
It would be a huge restructure, but if various elements (e.g. signs, players, etc.) were implemented with handler classes matching a simple interface (e.g. a getSignText method) Minecraft versions could be represented by a collection of objects matching the necessary implementations for each element. There could be a "PlainTextSignHandler", a "JsonSignHandler", a "SpigotJsonSignHandler", etc. This would allow a SignHandler to be associated with each Minecraft version, and replace the spaghetti with Factories that present the correct handler object for a given version (say in an enumeration of versions identifiers).

Of course, that's easier to say than to implement.

**Comment by skoeven** [comment]
That's an interesting idea.  I don't know that it's worth the work at the moment, maybe if signs change significantly again, but I'm hopeful that the MC devs have now stabilized on a sign text format that will stick around for a while.

The real problem is in handling the changes in texture packs and blocks over the different versions.  That's where a lot of the versioning spaghetti code is at.  A solution like you described might be useful in cleaning some of that mess up.  I'll have to think about it some more.

**Comment by swbr** [comment]
Hmmm. just to be clear: 

I guess textures & blocks depend on the MC version used by tectonicus. 
So once tectonicus runs, it knows which MC version it is, and how to handle textures & blocks.

BUT chunk data does not change unless MC loads this chunk and saves it again. To test, place a sign with one version and teleport far away. Load with an other MC version, place a sign and so on. You get a single map with all three sign text formats, as this printout of the raw NBT from tectonicus shows:

<pre>
 Line 1:MC 1.6.4
 Line 2:"=/\="
 Line 3:
 Line 4:

 Line 1:"MC 1.8.0"
 Line 2:"\"\u003d/\\\u003d\""
 Line 3:""
 Line 4:""

 Line 1:{"text":"MC 1.9.4"}
 Line 2:{"text":"\"\u003d/\\\u003d\""}
 Line 3:{"text":""}
 Line 4:{"text":""}
</pre>

So each sign has to be tested individually. And unless there's a way to know which MC version wrote a chunk, distinction is not 100% save. A sign from <1.8 could mime both other types, but... I wouldn't care.
And  `if (Minecraft.getMinecraftVersion() >= 1.8f)` doesn't really help.

**Comment by skoeven** [comment]
Ah, lovely, I didn't realize that.  I'll have to come up with a different strategy to deal with this, because as you said, checking for the version is useless.

**Comment by skoeven** [comment]
Hopefully, commit 7202367 should be a workable solution.  All the sign related version checking was removed. Signs that are from 1.7 or older may lose special characters in some circumstances, but they won't break the map anymore.
